name: Build Wattpilot Card

on:
  push:
    branches:
      - main  # upewnij się, że Twoja gałąź to 'main', jeśli używasz 'master' - zmień to tutaj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload compiled JS
        uses: actions/upload-artifact@v4 # ZMIANA: tutaj była wersja v3, teraz jest v4
        with:
          name: wattpilot-card-js
          path: dist/wattpilot-card.js
          overwrite: true # Opcjonalne: nadpisuje poprzedni artefakt
